<?php
/**
 * todo
 *
 * @copyright Copyright © 2021 Staempfli AG. All rights reserved.
 * @author    juan.alonso@staempfli.com
 */
use Magento\Framework\View\Element\Template;
/** @var Template $block */
?>
<div data-bind="scope: 'todo'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
        }
    }
</script>

